FROM fluent/fluentd:v1.2-debian
RUN apt-get update \
    && apt-get upgrade -y

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev build-essential" \
    && apt-get update \
    && apt-get install -y --no-install-recommends $buildDeps \
    && sudo gem install \
           fluent-plugin-bigquery -v "2.0.0.beta" \
    && sudo gem sources --clear-all \
    && SUDO_FORCE_REMOVE=yes \
       apt-get purge -y --auto-remove \
                     -o APT::AutoRemove::RecommendsImportant=false \
                     $buildDeps \
    && rm -rf /var/lib/apt/lists/* \
              /home/fluent/.gem/ruby/2.3.0/cache/*.gem

